name: Optimize Resource Pack & Release
permissions:
  contents: write

on:
  push:
    tags:
      - '**'

jobs:
  build:
    name: Optimize Resource Pack
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Run PackSquash
        uses: ComunidadAylas/PackSquash-action@v3
        with:
          path: pack
          artifact_name: optimized_pack_${{ github.run_id }}
          allow_optifine_mod: true
          maximum_image_width_and_height: 8192
      - name: Download optimized pack
        uses: actions/download-artifact@v3
        with:
          name: optimized_pack_${{ github.run_id }}
      - name: Rename pack file
        run: mv pack.zip ${{ github.ref_name }}.zip
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ github.ref_name }}.zip
